import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import WorldMap from "../../public/assets/world.png"

const inter = Inter({ subsets: ['latin'] })

const imageLoader = require("../../loader");

export default function Home() {
  return (
    <div className="bg-my_bg min-h-[960px] bg-contain bg-repeat-y px-20 py-3">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <div>
          {/* Logo */}
          <div>

          </div>

          {/* Navigation */}
          <div>

          </div>

          {/* Contact and flag */}
          <div>
            
          </div>
        </div>
      </main>
    </div>
  )
}
