import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Logo from "../../public/assets/logo.png"
import Flag from "../../public/assets/flag.png"

const inter = Inter({ subsets: ['latin'] })

const imageLoader = require("../../loader");

export default function Home() {
  return (
    <div className="bg-my_bg min-h-[960px] bg-contain bg-repeat-y px-20 py-3">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <div className='flex justify-between w-full'>
          {/* Left */}
          <div className='flex'>
            
            {/* Logo */}
            <div className='mr-8'>
              <Image loader={imageLoader} src={Logo} width={50} height={50} alt="logo" />
            </div>

            {/* Navigation */}
            <div>
              <ul className='flex space-x-4 items-center uppercase text-[#7C8A7F] font-bold justify-between h-full'>
                <li className='text-[#285430]'>
                  <a href='#'>Home</a>
                </li>
                <li>
                  <a href='#'>About Us</a>
                </li>
                <li>
                  <a href='#'>Services</a>
                </li>
                <li>
                  <a href='#'>Gallery</a>
                </li>
                <li>
                  <a href='#'>Career</a>
                </li>
              </ul>
            </div>
          </div>

          {/* Contact and flag */}
          {/* Right */}
          <div>
          <div className='flex items-center'>
            <div className='mr-2'>
              <Image loader={imageLoader} src={Flag} width={40} height={40} alt="logo" />
            </div>
            <div>
              <button className='bg-[#5FBF00] py-1 px-2 rounded-md text-[#3C493E] text-[0.8rem] font-bold'>
                CONTACT
              </button>
            </div>
            
          </div>
          </div>
        </div>
      </main>
    </div>
  )
}
